/**
 * Anonymous Feedback Board common types and abstractions.
 *
 * @module
 */

import { type MidnightProviders } from '@midnight-ntwrk/midnight-js-types';
import { type FoundContract } from '@midnight-ntwrk/midnight-js-contracts';
import type { State, FeedbackBoardPrivateState } from '../../contract/src/index';

export const feedbackBoardPrivateStateKey = 'feedbackBoardPrivateState';
export type PrivateStateId = typeof feedbackBoardPrivateStateKey;

export type PrivateStates = {
  readonly feedbackBoardPrivateState: FeedbackBoardPrivateState;
};

// Use any for contract type since the actual type is generated by Compact compiler
export type FeedbackBoardContract = any;

export type FeedbackBoardCircuitKeys = 'submitFeedback' | 'removeFeedback';

export type FeedbackBoardProviders = MidnightProviders<
  FeedbackBoardCircuitKeys,
  PrivateStateId,
  FeedbackBoardPrivateState
>;

export type DeployedFeedbackBoardContract = any;

export type FeedbackBoardDerivedState = {
  readonly state: State;
  readonly sequence: bigint;
  readonly totalSubmissions: bigint;
  readonly feedback: string | undefined;
  readonly isAuthor: boolean;
};
