// Auto-generated by Compact compiler - STUB FILE
// This file is generated when you run: npm run compact
// Replace this stub with the actual generated file after compiling the contract

export enum State {
  VACANT,
  OCCUPIED
}

export type Ledger = {
  readonly state: State;
  readonly feedback: {
    readonly is_some: boolean;
    readonly value?: string;
  };
  readonly totalSubmissions: bigint;
  readonly sequence: bigint;
  readonly authorHash: Uint8Array;
};

export const ledger = (data: unknown): Ledger => {
  // Stub implementation - replace with generated code
  return data as Ledger;
};

export const pureCircuits = {
  publicKey: (sk: Uint8Array, sequence: Uint8Array): Uint8Array => {
    // Stub implementation - replace with generated code
    return new Uint8Array(32);
  }
};

export interface Contract<PrivateState, W> {
  readonly impureCircuits: {
    readonly submitFeedback: readonly ['submitFeedback'];
    readonly removeFeedback: readonly ['removeFeedback'];
  };
}

export interface Witnesses<PrivateState> {
  readonly localSecretKey: readonly ['localSecretKey'];
}