// Auto-generated by Compact compiler - STUB FILE
// This file is generated when you run: npm run compact
// Replace this stub with the actual generated file after compiling the contract

// State enum
export const State = {
  VACANT: 0,
  OCCUPIED: 1
};

export const ledger = (data) => {
  // Stub implementation - replace with generated code
  return data;
};

export const pureCircuits = {
  publicKey: (sk, sequence) => {
    // Stub implementation - replace with generated code
    return new Uint8Array(32);
  }
};
