import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";

// Re-export contract types and runtime
export { State, ledger, pureCircuits } from "./managed/feedback-board/contract/index.js";
export type { Ledger, Contract as CompactContract } from "./managed/feedback-board/contract/index.js";

// Re-export witness types and implementations
export type { FeedbackBoardPrivateState } from "./witnesses";
export { createFeedbackBoardPrivateState, witnesses } from "./witnesses";

// Stub compiled contract - this will be replaced when npm run compact is executed
// The actual type is generated by the Compact compiler
export const CompiledFeedbackBoardContract: any = {
  // Stub properties
  witnesses: { localSecretKey: ['localSecretKey'] },
  circuits: { submitFeedback: ['submitFeedback'], removeFeedback: ['removeFeedback'] },
  provableCircuits: {},
  initialState: null
};
